# Generated by Django 6.0 on 2026-01-02 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_cartitem_unique_together_cartitem_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='review_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('invoice_created', 'Invoice Created'), ('payment_submitted', 'Payment Submitted'), ('payment_confirmed', 'Payment Confirmed'), ('payment_rejected', 'Payment Rejected'), ('complaint_created', 'Complaint Created'), ('complaint_updated', 'Complaint Updated'), ('complaint_resolved', 'Complaint Resolved'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('user_registered', 'New User Registered'), ('review_submitted', 'New Review Submitted'), ('question_submitted', 'New Question Submitted'), ('contact_message', 'New Contact Message')], max_length=30),
        ),
    ]
