# Generated by Django 6.0 on 2026-01-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_notification_contact_id_notification_question_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated delivery days')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('invoice_created', 'Invoice Created'), ('payment_submitted', 'Payment Submitted'), ('payment_confirmed', 'Payment Confirmed'), ('payment_rejected', 'Payment Rejected'), ('complaint_created', 'Complaint Created'), ('complaint_updated', 'Complaint Updated'), ('complaint_resolved', 'Complaint Resolved'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('user_registered', 'New User Registered'), ('review_submitted', 'New Review Submitted'), ('question_submitted', 'New Question Submitted'), ('contact_message', 'New Contact Message')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('awaiting_payment', 'Awaiting Payment'), ('payment_under_review', 'Payment Under Review'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='pending_confirmation', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='payments.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_notes/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payments.ordernote')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.shippingtype'),
        ),
    ]
