# Generated by Django 6.0 on 2026-01-07 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_shippingtype_order_confirmed_at_order_rejected_at_and_more'),
        ('products', '0004_alter_brand_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article du panier', 'verbose_name_plural': 'Articles du panier'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réclamation', 'verbose_name_plural': 'Réclamations'},
        ),
        migrations.AlterModelOptions(
            name='complaintattachment',
            options={'verbose_name': 'Pièce jointe de réclamation', 'verbose_name_plural': 'Pièces jointes de réclamations'},
        ),
        migrations.AlterModelOptions(
            name='complaintreason',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Motif de réclamation', 'verbose_name_plural': 'Motifs de réclamation'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Article de commande', 'verbose_name_plural': 'Articles de commande'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'verbose_name': 'Note de commande', 'verbose_name_plural': 'Notes de commande'},
        ),
        migrations.AlterModelOptions(
            name='ordernoteattachment',
            options={'verbose_name': 'Pièce jointe de note', 'verbose_name_plural': 'Pièces jointes de notes'},
        ),
        migrations.AlterModelOptions(
            name='paymentproof',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Preuve de paiement', 'verbose_name_plural': 'Preuves de paiement'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'verbose_name': 'Reçu de paiement', 'verbose_name_plural': 'Reçus de paiement'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Remboursement', 'verbose_name_plural': 'Remboursements'},
        ),
        migrations.AlterModelOptions(
            name='refundproof',
            options={'verbose_name': 'Preuve de remboursement', 'verbose_name_plural': 'Preuves de remboursement'},
        ),
        migrations.AlterModelOptions(
            name='refundreceipt',
            options={'verbose_name': 'Reçu de remboursement', 'verbose_name_plural': 'Reçus de remboursement'},
        ),
        migrations.AlterModelOptions(
            name='shippingtype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Type de livraison', 'verbose_name_plural': 'Types de livraison'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notes administrateur'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='custom_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motif personnalisé'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='payments.invoice', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='payments.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.complaintreason', verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Notes de résolution'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Résolue le'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('in_review', "En cours d'examen"), ('awaiting_user', 'En attente de réponse du client'), ('resolved', 'Résolue'), ('rejected', 'Rejetée')], default='open', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='complaintattachment',
            name='file',
            field=models.FileField(upload_to='complaint_attachments/%Y/%m/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='complaintattachment',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='Type de fichier'),
        ),
        migrations.AlterField(
            model_name='complaintreason',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='complaintreason',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='complaintreason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='complaintreason',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payée le'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_instructions',
            field=models.TextField(default="Veuillez effectuer le paiement via l'une des méthodes suivantes :\n1. BaridiMob : +213 XXX XXX XXX\n2. CCP : XXXXXX Clé XX\n3. Virement bancaire : IBAN DZXX XXXX XXXX XXXX XXXX\nAprès paiement, téléchargez votre preuve dans votre tableau de bord.", verbose_name='Instructions de paiement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Impayée'), ('payment_submitted', 'Paiement soumis'), ('payment_rejected', 'Paiement rejeté'), ('paid', 'Payée'), ('refunded', 'Remboursée')], default='unpaid', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.complaint', verbose_name='Réclamation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID du contact'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.invoice', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Commande créée'), ('invoice_created', 'Facture créée'), ('payment_submitted', 'Paiement soumis'), ('payment_confirmed', 'Paiement confirmé'), ('payment_rejected', 'Paiement rejeté'), ('complaint_created', 'Réclamation créée'), ('complaint_updated', 'Réclamation mise à jour'), ('complaint_resolved', 'Réclamation résolue'), ('refund_initiated', 'Remboursement initié'), ('refund_completed', 'Remboursement effectué'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('order_confirmed', 'Commande confirmée'), ('order_rejected', 'Commande rejetée'), ('user_registered', 'Nouvel utilisateur inscrit'), ('review_submitted', 'Nouvel avis soumis'), ('question_submitted', 'Nouvelle question soumise'), ('contact_message', 'Nouveau message de contact')], max_length=30, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de la question'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.refund', verbose_name='Remboursement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='review_id',
            field=models.IntegerField(blank=True, null=True, verbose_name="ID de l'avis"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Livrée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejetée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expédiée le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='Algérie', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(max_length=100, verbose_name='Wilaya'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.shippingtype', verbose_name='Type de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'En attente de confirmation'), ('confirmed', 'Confirmée'), ('rejected', 'Rejetée'), ('awaiting_payment', 'En attente de paiement'), ('payment_under_review', 'Paiement en cours de vérification'), ('paid', 'Payée'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refund_pending', 'Remboursement en attente'), ('refunded', 'Remboursée')], default='pending_confirmation', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de suivi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AlterField(
            model_name='ordernoteattachment',
            name='file',
            field=models.FileField(upload_to='order_notes/%Y/%m/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='ordernoteattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AlterField(
            model_name='ordernoteattachment',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='Type de fichier'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='payments.invoice', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_method',
            field=models.CharField(choices=[('baridimob', 'BaridiMob'), ('ccp_cheque', 'Chèque CCP'), ('bank_transfer', 'Virement bancaire'), ('cash_deposit', 'Dépôt en espèces'), ('other', 'Autre')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_file',
            field=models.FileField(upload_to='payment_proofs/%Y/%m/', verbose_name='Preuve de paiement'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence de transaction'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.complaint', verbose_name='Réclamation'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Effectué le'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.invoice', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('baridimob', 'BaridiMob'), ('ccp', 'CCP'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('other', 'Autre')], max_length=20, verbose_name='Méthode de remboursement'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('refund_pending', 'Remboursement en attente'), ('refund_approved', 'Remboursement approuvé'), ('refund_processing', 'Remboursement en cours'), ('refund_completed', 'Remboursement effectué'), ('refund_rejected', 'Remboursement rejeté')], default='refund_pending', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='refundproof',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='refundproof',
            name='proof_file',
            field=models.FileField(upload_to='refund_proofs/%Y/%m/', verbose_name='Preuve de remboursement'),
        ),
        migrations.AlterField(
            model_name='refundproof',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence de transaction'),
        ),
        migrations.AlterField(
            model_name='refundproof',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par'),
        ),
        migrations.AlterField(
            model_name='refundreceipt',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant remboursé'),
        ),
        migrations.AlterField(
            model_name='refundreceipt',
            name='refund_date',
            field=models.DateTimeField(verbose_name='Date de remboursement'),
        ),
        migrations.AlterField(
            model_name='refundreceipt',
            name='refund_method',
            field=models.CharField(max_length=20, verbose_name='Méthode de remboursement'),
        ),
        migrations.AlterField(
            model_name='shippingtype',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût'),
        ),
        migrations.AlterField(
            model_name='shippingtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shippingtype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='shippingtype',
            name='estimated_days',
            field=models.PositiveIntegerField(help_text='Délai de livraison estimé en jours'),
        ),
        migrations.AlterField(
            model_name='shippingtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='shippingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
