# Generated by Django 6.0 on 2026-01-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_cart_options_alter_cartitem_options_and_more'),
        ('products', '0005_bulkcontainertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant', verbose_name='Variante'),
        ),
    ]
