# Generated by Django 6.0 on 2025-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Support'), ('partnership', 'Partnership'), ('complaint', 'Complaint')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ordering', 'Ordering'), ('shipping', 'Shipping'), ('technical', 'Technical Support'), ('warranty', 'Warranties'), ('returns', 'Returns & Exchanges')], max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fennec Med', max_length=100)),
                ('tagline', models.CharField(default='Quality Medical Supplies', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(default='(123) 456-7890', max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(default='info@fennecmed.com', max_length=254)),
                ('address', models.TextField(default='123 Medical St, Brighton, VIC 3186')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('about_hero_title', models.CharField(default='Quality Medical Supplies You Can Trust', max_length=200)),
                ('about_hero_description', models.TextField(blank=True)),
                ('about_story_title', models.CharField(default='Our Story', max_length=200)),
                ('about_story_content', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL')),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('about_image_1', models.ImageField(blank=True, upload_to='site/about/')),
                ('about_image_2', models.ImageField(blank=True, upload_to='site/about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('ceo', 'CEO'), ('manager', 'Manager'), ('specialist', 'Medical Specialist'), ('technician', 'Technician'), ('sales', 'Sales Representative'), ('support', 'Customer Support')], default='support', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_about_page', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
