# Generated by Django 6.0 on 2026-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='tva_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='TVA/Tax rate as decimal (e.g., 0.19 for 19%)', max_digits=5),
        ),
    ]
