# Generated by Django 6.0 on 2026-01-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_siteinformation_tva_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'verbose_name': 'Informations du site', 'verbose_name_plural': 'Informations du site'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': "Membre de l'équipe", 'verbose_name_plural': "Membres de l'équipe"},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'Demande générale'), ('technical', 'Support technique'), ('partnership', 'Partenariat'), ('complaint', 'Réclamation')], max_length=20, verbose_name='Type de demande'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='responded',
            field=models.BooleanField(default=False, verbose_name='Répondu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('ordering', 'Commandes'), ('shipping', 'Livraison'), ('technical', 'Support technique'), ('warranty', 'Garanties'), ('returns', 'Retours et échanges')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about_hero_description',
            field=models.TextField(blank=True, verbose_name='Description principale de la page À propos'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about_hero_title',
            field=models.CharField(default='Fournitures médicales de qualité en qui vous pouvez avoir confiance', max_length=200, verbose_name='Titre principal de la page À propos'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about_image_1',
            field=models.ImageField(blank=True, upload_to='site/about/', verbose_name='Image À propos 1'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about_image_2',
            field=models.ImageField(blank=True, upload_to='site/about/', verbose_name='Image À propos 2'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about_story_content',
            field=models.TextField(blank=True, verbose_name="Contenu de l'histoire"),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about_story_title',
            field=models.CharField(default='Notre histoire', max_length=200, verbose_name="Titre de l'histoire"),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='address',
            field=models.TextField(default='123 Medical St, Brighton, VIC 3186', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='email',
            field=models.EmailField(default='info@fennecmed.com', max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text="URL d'intégration Google Maps", verbose_name='URL de la carte'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='phone',
            field=models.CharField(default='(123) 456-7890', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='site_name',
            field=models.CharField(default='Fennec Med', max_length=100, verbose_name='Nom du site'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='tagline',
            field=models.CharField(default='Fournitures médicales de qualité', max_length=200, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='tva_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Taux de TVA en décimal (ex. : 0,19 pour 19%)', max_digits=5, verbose_name='Taux de TVA'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='URL WhatsApp'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='URL YouTube'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to='team/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (les nombres inférieurs en premier)", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('founder', 'Fondateur'), ('ceo', 'Directeur général'), ('manager', 'Responsable'), ('specialist', 'Spécialiste médical'), ('technician', 'Technicien'), ('sales', 'Représentant commercial'), ('support', 'Support client')], default='support', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='show_on_about_page',
            field=models.BooleanField(default=True, verbose_name='Afficher sur la page À propos'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Note'),
        ),
    ]
