# Generated by Django 6.0 on 2026-01-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contactmessage_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='about_section_title',
            field=models.CharField(default='À Propos de Notre Cabinet Basé à Brighton', max_length=200, verbose_name="Titre section À propos (Page d'accueil)"),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='contact_form_description',
            field=models.TextField(default='Si vous préférez nous contacter par email, veuillez remplir vos coordonnées et nous vous répondrons bientôt.', verbose_name='Description formulaire (Page contact)'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='contact_form_title',
            field=models.CharField(default='Demande de Renseignements', max_length=200, verbose_name='Titre formulaire (Page contact)'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='contact_intro_text',
            field=models.TextField(blank=True, help_text="Texte d'introduction sur la page de contact", verbose_name='Texte intro (Page contact)'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='contact_intro_title',
            field=models.CharField(default="Contactez l'Équipe", max_length=200, verbose_name='Titre intro (Page contact)'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='cta_description',
            field=models.TextField(default="Contactez-nous aujourd'hui pour en savoir plus sur nos matériaux médicaux et services.", verbose_name="Description CTA (Page d'accueil)"),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='cta_title',
            field=models.CharField(default='Prêt à Franchir la Prochaine Étape ?', max_length=200, verbose_name="Titre CTA (Page d'accueil)"),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='find_us_content',
            field=models.TextField(blank=True, help_text="Texte pour la section 'Où Nous Trouver' sur la page d'accueil", verbose_name="Contenu 'Où Nous Trouver' (Page d'accueil)"),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='hero_subtitle',
            field=models.TextField(default='Fournisseur de matériaux médicaux de qualité aux familles de la région depuis 2022.', verbose_name="Sous-titre Hero (Page d'accueil)"),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='hero_title',
            field=models.CharField(default='Bienvenue chez Fennec Med', max_length=200, verbose_name="Titre Hero (Page d'accueil)"),
        ),
    ]
