# Generated by Django 6.0 on 2026-01-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_siteinformation_about_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text="URL d'intégration Google Maps", max_length=1000, verbose_name='URL de la carte'),
        ),
    ]
