# Generated by Django 6.0 on 2026-01-07 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicprofile',
            options={'verbose_name': 'profil clinique', 'verbose_name_plural': 'profils cliniques'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'profil médecin', 'verbose_name_plural': 'profils médecins'},
        ),
        migrations.AlterModelOptions(
            name='pharmacyprofile',
            options={'verbose_name': 'profil pharmacie', 'verbose_name_plural': 'profils pharmacies'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil utilisateur', 'verbose_name_plural': 'profils utilisateurs'},
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='limite budgétaire'),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='clinic_name',
            field=models.CharField(max_length=200, verbose_name='nom de la clinique'),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='department',
            field=models.CharField(max_length=100, verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='employee_id',
            field=models.CharField(max_length=50, verbose_name='identifiant employé'),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='position',
            field=models.CharField(max_length=100, verbose_name='poste'),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='supervisor_email',
            field=models.EmailField(max_length=254, verbose_name='email du superviseur'),
        ),
        migrations.AlterField(
            model_name='clinicprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='credentials',
            field=models.TextField(verbose_name='diplômes et certifications'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_affiliation',
            field=models.CharField(max_length=200, verbose_name="hôpital d'affiliation"),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license',
            field=models.CharField(max_length=100, verbose_name='numéro de licence médicale'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('dermatology', 'Dermatologie'), ('ophthalmology', 'Ophtalmologie'), ('nephrology', 'Néphrologie'), ('cardiology', 'Cardiologie'), ('orthopedics', 'Orthopédie'), ('neurology', 'Neurologie'), ('pediatrics', 'Pédiatrie'), ('general', 'Médecine générale')], max_length=50, verbose_name='spécialité'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='vérifié'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(verbose_name="années d'expérience"),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='business_registration',
            field=models.CharField(max_length=100, verbose_name="numéro d'enregistrement commercial"),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_expiry',
            field=models.DateField(verbose_name="date d'expiration de la licence"),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_number',
            field=models.CharField(max_length=100, verbose_name='numéro de licence'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='pharmacy_name',
            field=models.CharField(max_length=200, verbose_name='nom de la pharmacie'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='verification_documents',
            field=models.FileField(blank=True, upload_to='pharmacy_docs/', verbose_name='documents de vérification'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='vérifié'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='photo de profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='état/province'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('general', 'Utilisateur général'), ('pharmacy', 'Personnel de pharmacie'), ('clinic', 'Personnel de clinique'), ('doctor', 'Médecin')], default='general', max_length=20, verbose_name="type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code postal'),
        ),
    ]
