# Generated by Django 6.0 on 2026-01-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('typical_capacity', models.CharField(blank=True, help_text='Ex: 50 unités, 10L, etc.', max_length=100, verbose_name='Capacité typique')),
            ],
            options={
                'verbose_name': 'Type de conteneur en gros',
                'verbose_name_plural': 'Types de conteneurs en gros',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='additional_cost',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_type',
            field=models.CharField(choices=[('retail', 'Détail'), ('bulk', 'En Gros')], default='retail', max_length=10, verbose_name="Type d'achat"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de détail'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'une seule unité de détail", max_digits=10, null=True, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='units_per_container',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités de détail dans ce conteneur", null=True, verbose_name='Unités par conteneur'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix du conteneur complet', max_digits=10, null=True, verbose_name='Prix de gros'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix en gros (legacy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='Quantité en gros (legacy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='bulk_container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.bulkcontainertype', verbose_name='Type de conteneur'),
        ),
    ]
